version: "3"
services:
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./web/apps/staticfiles/:/staticfiles
    ports:
      - "80:80"
    networks:
      - my-net
    depends_on:
      - web

  web:
    build: ./web
    container_name: web
    command: "/bin/bash /apps/entrypoint.sh"
    env_file:
      - ./web/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    networks:
      - my-net

networks:
  my-net:
    external: true