# Generated by Django 4.2.1 on 2023-06-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_seq', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default='-', max_length=100)),
                ('brand_link', models.CharField(default='-', max_length=300)),
            ],
            options={
                'db_table': 'brands',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_seq', models.AutoField(primary_key=True, serialize=False)),
                ('hash_name', models.CharField(default='-', max_length=100)),
                ('hash_avg_price', models.IntegerField(default=0)),
                ('room_type', models.CharField(default='-', max_length=4)),
                ('hash_desc', models.CharField(default='-', max_length=1000)),
                ('hash_thumbnail', models.CharField(default='-', max_length=300)),
                ('is_active', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'hashtags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HashtagCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hash_cate_seq', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='-', max_length=45)),
                ('room_type', models.CharField(default='-', max_length=4)),
                ('thumbnail', models.CharField(default='-', max_length=300)),
                ('description', models.CharField(default='-', max_length=100)),
            ],
            options={
                'db_table': 'hashtagCategories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_seq', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(default='-', max_length=100)),
                ('prod_link', models.CharField(default='-', max_length=300)),
                ('prod_price', models.IntegerField(default=0)),
                ('prod_discount', models.IntegerField(default=0)),
                ('prod_thumbnail', models.CharField(default='-', max_length=300)),
                ('brand_seq', models.ForeignKey(db_column='brand_seq', on_delete=django.db.models.deletion.PROTECT, to='products.brand')),
            ],
            options={
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductHashtag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_hash_seq', models.AutoField(primary_key=True, serialize=False)),
                ('hash_seq', models.ForeignKey(db_column='hash_seq', on_delete=django.db.models.deletion.PROTECT, to='products.hashtag')),
                ('prod_seq', models.ForeignKey(db_column='prod_seq', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'productHashtags',
                'managed': True,
            },
        ),
    ]
