# Generated by Django 4.2.1 on 2023-06-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_src_comp_alter_product_prod_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHashtag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_hash_seq', models.AutoField(primary_key=True, serialize=False)),
                ('hash_seq', models.ForeignKey(db_column='hash_seq', on_delete=django.db.models.deletion.PROTECT, to='products.hashtag')),
                ('prod_seq', models.ForeignKey(db_column='prod_seq', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'db_table': 'productHashtags',
                'managed': True,
            },
        ),
    ]
