# Generated by Django 4.2.1 on 2023-06-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producthashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='src_comp',
        ),
    ]
