# Generated by Django 4.2.1 on 2023-06-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_src_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='hash_thumbnail',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
